language: php

php:
  - 7.3

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  global:
    - PLUGIN_NAME=CakeSettingsApp
    - REQUIRE="anklimsk/cakephp-console-installer dereuromark/cakephp-queue:^2.3.0"
    - DB=mysql
    - CAKE_REF=2.x
    - PHPUNIT=5.7.19

services:
  - mysql

matrix:
  include:
    - php: 7.3
      env:
        - CODECOVERAGE=1
    - php: 7.3
      env:
        - PHPCS=1
        - PHPCS_IGNORE=CakeInstaller,CakeBasicFunctions,CakeExtendTest,CakeConfigPlugin,CakeTheme,AssetCompress,Bs3Helpers,Queue,Shim,Tools
    - php: 7.3
      env:
        - FOC_VALIDATE=1

before_script:
  - git clone -b master https://github.com/FriendsOfCake/travis.git --depth 1 ../travis
  - travis_wait ../travis/before_script.sh
  - if [ -d "../cakephp/app/Vendor/PHPUnit" ]; then rm -rf ../cakephp/app/Vendor/PHPUnit; fi
  - pear config-set preferred_state snapshot && yes "" | pecl install mcrypt
  - cd ../cakephp; composer require "phpunit/phpunit=$PHPUNIT"; echo "require_once ROOT . '/vendors/autoload.php';" >> app/Config/bootstrap.php; cd -
  - if [ -f "../cakephp/app/Console/cake" ]; then ../cakephp/app/Console/cake CakeInstaller setsecurkey --yes --app $(cd ../cakephp/app; pwd); fi
  - if [ -f "../cakephp/app/Config/database.php" ]; then sed -i -r "/$test = array\(/a 'encoding' => 'utf8'," ../cakephp/app/Config/database.php; sed -i -e "s/'host' => '0\.0\.0\.0'/'host' => '127\.0\.0\.1'/g" ../cakephp/app/Config/database.php; fi
  - if [ -f "../cakephp/app/Plugin/CakeTheme/Config/asset_compress.local.ini" ]; then cp "../cakephp/app/Plugin/CakeTheme/Config/asset_compress.local.ini" "../cakephp/app/Config/asset_compress.ini"; fi

script:
  - ../travis/script.sh

after_success:
  - if [ -f "../cakephp/app/clover.xml" ]; then cp ../cakephp/app/clover.xml ../cakephp/app/Plugin/$PLUGIN_NAME; fi
  - if [ -d "../cakephp/app/Plugin/$PLUGIN_NAME" ]; then cd ../cakephp/app/Plugin/$PLUGIN_NAME; fi
  - if [ "$CODECOVERAGE" == '1' ]; then wget -O codecov.sh https://codecov.io/bash; bash codecov.sh; fi

notifications:
  email: false
